name: Speculative Run

on:
  workflow_dispatch:
    inputs:
      workspace_transfer_url:
        description: "URL from which to download the workspace"
        required: true
        type: string

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=github-releases depName=hashicorp/terraform
      TERRAFORM_VERSION: "1.6.6"
      TF_HTTP_PASSWORD: ${{ github.token }}
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Download Workspace
        run: |
          curl ${{ inputs.workspace_transfer_url }} --user github_pat:${TF_HTTP_PASSWORD} --fail --silent | tar -xzf -
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${TERRAFORM_VERSION}
      - run: terraform init
      - run: terraform plan
