name: Speculative Run

on:
  workflow_dispatch:
    inputs:
      webrtc-session:
        description: "Session (base64 encoded) for the workspace download over webrtc"
        required: true
        type: string

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-22.04
    env:
      TF_HTTP_PASSWORD: ${{ github.token }}
      TF_IN_AUTOMATION: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download Workspace
        run: |
          go run ./cmd/webrtc-downloader -session ${{ inputs.webrtc-session }}
      - run: tar -ztvf workspace.tar.gz
      # - uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: "1.6.6"
      # - run: terraform init
      # - run: terraform plan
